name: MSYS2
on: [push]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          echo 'PWD' | pwd
          g++ --version
          g++ -E ./code/test.cpp -o out
          echo 'PWD' | pwd
          echo 'LS' | ls
          out.exe
